interface AutoMessage {
  callback: string;
  chatbubbleUrl1: string;
  chatbubbleUrl2: string;
  chatbubbleUrl3: string;
  chatbubbleUrl4: string;
  chatbubbleUrl5: string;
  compkey: string;
  createDate: string;
  etc1: string;
  etc2: string;
  etc3: string;
  etc4: number;
  etc5: string;
  etc6: string;
  expireTime: string;
  fileCnt: number;
  filePath1: string;
  filePath2: string;
  filePath3: string;
  filePath4: string;
  filePath5: string;
  fileSize1: number;
  fileSize2: number;
  fileSize3: number;
  fileSize4: number;
  fileSize5: number;
  id: string;
  imgLink: string;
  imgUrl: string;
  msg: string;
  msgId: number;
  phone: string;
  post: string;
  reportDate: string;
  reqDate: string;
  resend: string;
  rslt: string;
  rsltDate: string;
  rsltResend: string;
  sentDate: string;
  status: string;
  subject: string;
  telcoInfo: string;
  template: string;
  terminatedDate: string;
  tmplCd: string;
  type: "SMS" | "LMS" | "MMS" | "KKT";
  updateDate: string;
  yellowIdKey: string;
}

export default AutoMessage;
